---
concepts:
  title: concepts
  sections:
  - title: type
    entity:
      name: concepts
      fallback: true
    fields:
    - proxies.dcType
    search_field: type
    quoted: true
  - title: subject
    entity:
      name: concepts
      fallback: true
    fields:
    - proxies.dcSubject
    search_field: what
    quoted: true
  - title: has-type
    search_field: type
    fields:
    - proxies.edmHasType
  - title: medium
    search_field: proxy_dcterms_medium
    quoted: true
    fields: proxies.dctermsMedium
copyright:
  title: additional-rights
  sections:
  - title: rights
    fields:
    - proxies.dcRights
    ga_data: dimension5
time:
  title: time
  sections:
  - title: date
    fields:
    - proxies.dcDate
  - title: creation-date
    fields:
    - proxies.dctermsIssued
    - proxies.dctermsCreated
  - title: period
    fields:
    - timespans.prefLabel
  - title: publication-date
    fields:
    - proxies.dctermsPublished
  - title: issued
    fields:
    - proxies.dctermsIssued
  - title: temporal
    entity:
      name: timespans
      extra:
      - field: begin
      - field: end
    fields:
    - proxies.dctermsTemporal
  - title: place-time
    fields:
    - proxies.dcCoverage
description:
  title: description
  sections:
  - fields:
    - proxies.dctermsTOC
  - fields:
    - proxies.dcDescription
location:
  title: location
  sections:
  - title: location
    entity:
      name: places
    fields:
    - proxies.dctermsSpatial
  - title: place-time
    fields:
    - proxies.dcCoverage
  - title: current-location
    fields:
    - proxies.edmCurrentLocation
people:
  title: people
  sections:
  - title: creator
    entity:
      name: agents
      fallback: true
      extra:
      - field: rdaGr2DateOfBirth
        map_to: life.from.short
        format_date: "%Y-%m-%d"
      - field: rdaGr2DateOfDeath
        map_to: life.to.short
        format_date: "%Y-%m-%d"
    fields:
    - proxies.dcCreator
    search_field: who
  - title: contributor
    entity:
      name: agents
      fallback: true
      extra:
      - field: rdaGr2DateOfBirth
        map_to: life.from.short
        format_date: "%Y-%m-%d"
      - field: rdaGr2DateOfDeath
        map_to: life.to.short
        format_date: "%Y-%m-%d"
    fields:
    - proxies.dcContributor
    search_field: who
  - title: subject
    entity:
      name: agents
    fields:
    - proxies.dcSubject
    search_field: who
  - title: publisher
    entity:
      name: agents
    fields:
    - proxies.dcPublisher
    search_field: who
  - title: rights
    entity:
      name: agents
    fields:
    - proxies.dcRights
    search_field: who
provenance:
  title: provenance
  sections:
  - title: source
    fields:
    - aggregations.edmUgc
    map_values:
      "true": site.object.meta-label.ugc
    exclude_vals:
    - "false"
  - title: provenance
    fields:
    - proxies.dctermsProvenance
  - title: provenance
    fields:
    - proxies.dcSource
    exclude_vals:
    - ugc
    - UGC
  - title: publisher
    fields:
    - proxies.dcPublisher
    search_field: proxy_dc_publisher
    quoted: true
  - title: identifier
    fields:
    - proxies.dcIdentifier
  - title: data-provider
    fields:
    - aggregations.edmDataProvider
    search_field: DATA_PROVIDER
    ga_data: dimension3
    quoted: true
  - title: intermediate-provider
    fields:
    - aggregations.edmIntermediateProvider
    search_field: false
  - title: provider
    fields:
    - aggregations.edmProvider
    search_field: PROVIDER
    ga_data: dimension4
    quoted: true
  - title: providing-country
    fields:
    - europeanaAggregation.edmCountry
    search_field: COUNTRY
    ga_data: dimension2
    quoted: true
    capitalised: true
  - title: timestamp-created
    fields:
    - timestamp_created
    format_date: "%Y-%m-%d"
  - title: timestamp-updated
    fields:
    - timestamp_update
    format_date: "%Y-%m-%d"
properties:
  title: properties
  sections:
  - title: extent
    fields:
    - proxies.dctermsExtent
  - title: duration
    fields:
    - proxies.dcDuration
  - title: medium
    fields:
    - proxies.dcMedium
  - title: format
    fields:
    - proxies.dcFormat
    entity:
      name: concepts
      fallback: true
    search_field: proxy_dc_format
    quoted: true
  - title: language
    fields:
    - proxies.dcLanguage
    search_field: dc_language
    quoted: false
refs_rels:
  title: refs-rels
  sections:
  - title: is-part-of
    fields:
    - proxies.dctermsIsPartOf
    search_field: proxy_dcterms_isPartOf
    quoted: true
  - title: collection-name
    fields:
    - europeanaCollectionName
    search_field: europeana_collectionName
  - title: relations
    fields:
    - proxies.dcRelation
  - title: references
    fields:
    - proxies.dctermsReferences
  - title: consists-of
    fields:
    - proxies.dctermsHasPart
    max: 10
  - title: version
    fields:
    - proxies.dctermsHasVersion
  - title: is-format-of
    fields:
    - proxies.dctermsIsFormatOf
  - title: is-referenced-by
    fields:
    - proxies.dctermsIsReferencedBy
  - title: is-replaced-by
    fields:
    - proxies.dctermsIsReplacedBy
  - title: is-required-by
    fields:
    - proxies.dctermsIsRequiredBy
  - title: edm.has-met
    fields:
    - proxies.edmHasMet
  - title: edm.incorporates
    fields:
    - proxies.edmIncorporates
  - title: edm.is-derivative-of
    fields:
    - proxies.edmIsDerivativeOf
  - title: edm.is-representation-of
    fields:
    - proxies.edmIsRepresentationOf
  - title: edm.is-similar-to
    fields:
    - proxies.edmIsSimilarTo
  - title: edm.is-successor-of
    fields:
    - proxies.edmIsSuccessorOf
  - title: edm.realises
    fields:
    - proxies.edmRealizes
  - title: edm.was-present-at
    fields:
    - proxies.wasPresentAt
