# From https://docs.run.pivotal.io/marketplace/external-ips.html
production:
- 54.84.85.220
- 54.84.112.162
- 54.85.141.236
- 54.86.187.144
- 54.86.233.33
- 54.88.36.32
- 54.88.9.119
- 54.88.42.21
- 54.88.46.179
- 54.208.167.186
- 54.209.85.236
- 54.236.219.204
