---
:hero: music.jpg
:query: ! '"DISMARC+-+EuropeanaConnect" OR PROVIDER: "Cit√©+de+la+musique" OR PROVIDER:
  "IRCAM-Institut+de+Recherche+et+Coordination+Acoustique%2FMusique" OR (what: Music)
  OR (what: Sheet Music) OR (what: Musical Instrument)'
